### ISSUE TITLE
Unpinned dependencies make builds not reproducible

### ISSUE THREAD

**Issue by lorisercole** [ExaChem/exachem#4]
We built and used this code (and TAMM) many times in the past year, however, making consistently working builds has been almost impossible.
The problem is that dependencies are not pinned to specific versions.
CMake will use the latest https://github.com/NWChemEx/CMakeBuild, which will install the `develop/master` version of many packages. Even if I fixed the version of ExaChem/TAMM/CMakeBuild I wanted to use, I am not guaranteed to obtain a working build if the dependencies change (and they do change).

On top of that, ExaChem/TAMM/CMakeBuild themselves are not stable yet, so it is very hard to deploy in a production environment.
It would be very valuable if the developers could make a tagged pre-release in which all the dependencies are pinned and guaranteed to work with each other.
I hope this feedback helps! Thanks.

**Comment by ajaypanyala** [comment]
@lorisercole Thanks for the feedback! This is intentional since we wanted users to always use the latest versions of `ExaChem` and it's dependencies mainly due to the rapidly evolving nature of the codebase (which includes other reasons). However, we understand that some users might prefer to use a specific tag and stick with it for consistency. Starting today, you can use the tag `2024-06-12` for both `ExaChem` and `TAMM`. We will create tags more frequently going forward. All dependencies that get pulled are also pinned (if they were not previously) to specific commits/releases. You do need to add an extra option `-DCMSB_TAG=<tag-name>` to your cmake configure line when using a specific tag of `ExaChem/TAMM` as indicated [here](https://exachem.readthedocs.io/en/latest/install.html#build-instructions-for-a-quick-start)

**Comment by lorisercole** [comment]
Thanks @ajaypanyala! This is very helpful.
I will try to recompile the code and get back to you if I have any problem.
